#!/bin/bash
echo "🔐 Password Book"
echo ""
echo "启动本地服务器（server.js，默认端口 3457）："
echo ""
echo "  node server.js"
echo ""
echo "然后在浏览器中访问："
echo ""
echo "  http://127.0.0.1:3457"
echo ""
echo "或者直接用浏览器打开项目目录里的 index.html"
echo ""
read -p "按 Enter 打开浏览器..." 
open http://127.0.0.1:3457/
